
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-04
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-04
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ5ODgzNjQy","is_bot":false,"login":"jeremiahwong704","name":"Jeremiah Wong"},"headRefName":"Jeremiah-Menu-Endpoint","number":33,"title":"Add an Individual Menu Item Endpoint","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/33"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-Reviews-Placeholder-Page","number":32,"title":"Add a Placeholder page for Reviews","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/32"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-Create-Reviews-Table","number":31,"title":"Create a Review Table","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/31"},{"author":{"id":"U_kgDOCvDiEw","is_bot":false,"login":"ZFahim10","name":""},"headRefName":"Fahim-ModeratorBackend","number":30,"title":"Backend Code for Moderator Role","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/30"}]
