
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-04
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-04
pull_requests: [{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-MyReviews-Page","number":46,"title":"Add MyReviews page","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/46"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Alias-Approval-Table","number":40,"title":"RZ-Add an Alias Approval Table","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/40"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-Add_Avg_Ratings","number":39,"title":"Montgomery add avg ratings","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-04/pull/39"}]
